### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [BenDol/fantasy-mounts-wiki#2]
`Minecraft v1.16.5`
`Forge v36.0.13`
`Fantasy Mounts v1.0.1b`

The item tooltip is causing a server crash.
[Crash Report](https://gist.github.com/WenXin20/0917bf5bcab6f4eeaf9d31651da1e1b6)

**Comment by BenDol** [comment]
Thank you for reporting this issue, do you know which item's tooltip is causing this issue?

**Comment by WenXin20** [comment]
I don't know, it could be all of them since it crashes during server load.

**Comment by BenDol** [comment]
I see, I will take a look now

**Comment by BenDol** [comment]
So I wonder if there's interference happen with one of the mods you're using? I can't seem to reproduce the issue. Are you able to test it out with the same versions, etc but without any other mods? Otherwise perhaps you could share the modpack you're using with me?

**Comment by BenDol** [comment]
Actually I think I know what's going on

**Comment by BenDol** [comment]
Submitted a patch for this issue https://www.curseforge.com/minecraft/mc-mods/fantasy-mounts/files/3193944

Feel free to reopen this issue if it still persists!

**Comment by WenXin20** [comment]
Thanks!
